version: "3.8"

services:
  app:
    build:
      context: .
    container_name: discord-clone
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/discord_db"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - discord

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: discord_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker-compose/mysql/data:/var/lib/mysql
      - ./docker-compose/mysql/logs:/var/log/mysql
      - ./docker-compose/mysql/ql:/docker-entrypoint-initdb.d
    networks:
      - discord
  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    image: nginx:alpine
    container_name: nginx-jax-laravel
    restart: unless-stopped
    ports:
      - 81:81
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - ./docker-compose/nginx/ssl:/etc/nginx/conf.d/ssl
      - ./docker-compose/nginx/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf
    networks:
      - discord
  ####################################################################################################
  # phpMyAdmin
  ####################################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-discord
    ports:
      - 8081:80
    links:
      - db
    restart: unless-stopped
    environment:
      PMA_HOST: db
      #PMA_USER: ${DB_USERNAME}
      #PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - discord
networks:
  discord:
    driver: bridge
